apiVersion: apps/v1
kind: Deployment
metadata:
  name: europeana-frontend-deployment
  labels:
    app: europeana_frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: europeana_frontend
  template:
    metadata:
      labels:
        app: europeana_frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: SEARCH_URL
            value: "35.229.56.157"
        #imagePullPolicy: Never
